version: "3.3"

services:
  keycloak:
    image: jboss/keycloak:18.0.2
    command:
      - start-dev
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "1234"
      DEBUG: "true"
      DEBUG_PORT: "*:8787"
    ports:
    - 8080:8080
    - 5005:8787
    volumes:
    - ./target/libs/RegistrationUsername-1.2.jar:/opt/jboss/keycloak/standalone/deployments/RegistrationUsername-1.2.jar
